name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Atau ganti dengan 'master' jika Anda menggunakan master sebagai default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Menggunakan secret GH_TOKEN yang sudah ditambahkan
          publish_dir: ./dist
